package com.arc.cloud.dao.hib2.hib.codegen;
// Generated 23-Nov-2015 8:39:18 AM by Hibernate Tools 4.3.1.Final



/**
 * Archiveaudit generated by hbm2java
 */
public class Archiveaudit  implements java.io.Serializable {


     private int id;
     private String operationtext;
     private String audittime;
     private String auditedby;

    public Archiveaudit() {
    }

	
    public Archiveaudit(int id) {
        this.id = id;
    }
    public Archiveaudit(int id, String operationtext, String audittime, String auditedby) {
       this.id = id;
       this.operationtext = operationtext;
       this.audittime = audittime;
       this.auditedby = auditedby;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getOperationtext() {
        return this.operationtext;
    }
    
    public void setOperationtext(String operationtext) {
        this.operationtext = operationtext;
    }
    public String getAudittime() {
        return this.audittime;
    }
    
    public void setAudittime(String audittime) {
        this.audittime = audittime;
    }
    public String getAuditedby() {
        return this.auditedby;
    }
    
    public void setAuditedby(String auditedby) {
        this.auditedby = auditedby;
    }




}


