package com.arc.cloud.dao.hib2.hib.codegen;
// Generated 23-Nov-2015 8:39:18 AM by Hibernate Tools 4.3.1.Final


import java.util.Date;

/**
 * Inbox generated by hbm2java
 */
public class Inbox  implements java.io.Serializable {


     private int id;
     private Customers customers;
     private String title;
     private String content;
     private Boolean status;
     private Date createdt;

    public Inbox() {
    }

	
    public Inbox(int id) {
        this.id = id;
    }
    public Inbox(int id, Customers customers, String title, String content, Boolean status, Date createdt) {
       this.id = id;
       this.customers = customers;
       this.title = title;
       this.content = content;
       this.status = status;
       this.createdt = createdt;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Customers getCustomers() {
        return this.customers;
    }
    
    public void setCustomers(Customers customers) {
        this.customers = customers;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    public Boolean getStatus() {
        return this.status;
    }
    
    public void setStatus(Boolean status) {
        this.status = status;
    }
    public Date getCreatedt() {
        return this.createdt;
    }
    
    public void setCreatedt(Date createdt) {
        this.createdt = createdt;
    }




}


