package com.arc.cloud.dao.hib.codegen;
// Generated 11-Nov-2015 9:38:24 AM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Organization generated by hbm2java
 */
public class Organization implements java.io.Serializable {

	private long id;
	private String orgname;
	private String orgaddr1;
	private String orgaddr2;
	private String orgstate;
	private String orgzip;
	private String orgcountry;
	private String creditcardno;
	private String creditcardexpdt;
	private String creditcardcvv;
	private Set customerses = new HashSet(0);

	public Organization() {
	}

	public Organization(long id) {
		this.id = id;
	}

	public Organization(long id, String orgname, String orgaddr1, String orgaddr2, String orgstate, String orgzip,
			String orgcountry, String creditcardno, String creditcardexpdt, String creditcardcvv, Set customerses) {
		this.id = id;
		this.orgname = orgname;
		this.orgaddr1 = orgaddr1;
		this.orgaddr2 = orgaddr2;
		this.orgstate = orgstate;
		this.orgzip = orgzip;
		this.orgcountry = orgcountry;
		this.creditcardno = creditcardno;
		this.creditcardexpdt = creditcardexpdt;
		this.creditcardcvv = creditcardcvv;
		this.customerses = customerses;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getOrgname() {
		return this.orgname;
	}

	public void setOrgname(String orgname) {
		this.orgname = orgname;
	}

	public String getOrgaddr1() {
		return this.orgaddr1;
	}

	public void setOrgaddr1(String orgaddr1) {
		this.orgaddr1 = orgaddr1;
	}

	public String getOrgaddr2() {
		return this.orgaddr2;
	}

	public void setOrgaddr2(String orgaddr2) {
		this.orgaddr2 = orgaddr2;
	}

	public String getOrgstate() {
		return this.orgstate;
	}

	public void setOrgstate(String orgstate) {
		this.orgstate = orgstate;
	}

	public String getOrgzip() {
		return this.orgzip;
	}

	public void setOrgzip(String orgzip) {
		this.orgzip = orgzip;
	}

	public String getOrgcountry() {
		return this.orgcountry;
	}

	public void setOrgcountry(String orgcountry) {
		this.orgcountry = orgcountry;
	}

	public String getCreditcardno() {
		return this.creditcardno;
	}

	public void setCreditcardno(String creditcardno) {
		this.creditcardno = creditcardno;
	}

	public String getCreditcardexpdt() {
		return this.creditcardexpdt;
	}

	public void setCreditcardexpdt(String creditcardexpdt) {
		this.creditcardexpdt = creditcardexpdt;
	}

	public String getCreditcardcvv() {
		return this.creditcardcvv;
	}

	public void setCreditcardcvv(String creditcardcvv) {
		this.creditcardcvv = creditcardcvv;
	}

	public Set getCustomerses() {
		return this.customerses;
	}

	public void setCustomerses(Set customerses) {
		this.customerses = customerses;
	}

}
