package com.arc.cloud.dao.hib.codegen;
// Generated 10-Nov-2015 7:33:19 PM by Hibernate Tools 4.3.1.Final

/**
 * Project generated by hbm2java
 */
public class Project implements java.io.Serializable {

	private int id;
	private String projectname;
	private String projectdesc;
	private Integer orgid;

	public Project() {
	}

	public Project(int id) {
		this.id = id;
	}

	public Project(int id, String projectname, String projectdesc, Integer orgid) {
		this.id = id;
		this.projectname = projectname;
		this.projectdesc = projectdesc;
		this.orgid = orgid;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getProjectname() {
		return this.projectname;
	}

	public void setProjectname(String projectname) {
		this.projectname = projectname;
	}

	public String getProjectdesc() {
		return this.projectdesc;
	}

	public void setProjectdesc(String projectdesc) {
		this.projectdesc = projectdesc;
	}

	public Integer getOrgid() {
		return this.orgid;
	}

	public void setOrgid(Integer orgid) {
		this.orgid = orgid;
	}

}
