package com.arc.cloud.dao.hib.codegen;
// Generated 10-Nov-2015 7:33:19 PM by Hibernate Tools 4.3.1.Final

/**
 * Taxonomy generated by hbm2java
 */
public class Taxonomy implements java.io.Serializable {

	private int id;
	private String projectid;
	private String subdivision1;
	private String subdivision2;
	private Integer orgid;

	public Taxonomy() {
	}

	public Taxonomy(int id) {
		this.id = id;
	}

	public Taxonomy(int id, String projectid, String subdivision1, String subdivision2, Integer orgid) {
		this.id = id;
		this.projectid = projectid;
		this.subdivision1 = subdivision1;
		this.subdivision2 = subdivision2;
		this.orgid = orgid;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getProjectid() {
		return this.projectid;
	}

	public void setProjectid(String projectid) {
		this.projectid = projectid;
	}

	public String getSubdivision1() {
		return this.subdivision1;
	}

	public void setSubdivision1(String subdivision1) {
		this.subdivision1 = subdivision1;
	}

	public String getSubdivision2() {
		return this.subdivision2;
	}

	public void setSubdivision2(String subdivision2) {
		this.subdivision2 = subdivision2;
	}

	public Integer getOrgid() {
		return this.orgid;
	}

	public void setOrgid(Integer orgid) {
		this.orgid = orgid;
	}

}
